set PROJECT_PATH=D:/Magento/ce/v2.3.4

set MYSQL_HOST=localhost
set MYSQL_USERNAME=root
set MYSQL_PASSWORD=root
set MYSQL_DATABASE=magento-ce-2-3-4

set MAGENTO_BASE_URL=http://magento-ce-2-3-4.local
set MAGENTO_BACKEND_FRONTNAME=admin
set MAGENTO_ADMIN_USER=admin
set MAGENTO_ADMIN_PASSWORD=admin123
set MAGENTO_ADMIN_FIRSTNAME=admin
set MAGENTO_ADMIN_LASTNAME=admin
set MAGENTO_ADMIN_EMAIL=noreply@domain.com
set MAGENTO_LANGUAGE=en_US
set MAGENTO_CURRENCY=USD
set MAGENTO_TIMEZONE=America/Los_Angeles

set MAGENTO_VERSION=2.3.4
set MAGENTO_EDITION=community
set MAGENTO_PUBLIC_KEY=4ddf97a47e281f624805bea8487da642
set MAGENTO_PRIVATE_KEY=3ac9fe3a3a139e105935f073107762b1
