#!/bin/bash

# Enable maintenance mode
php bin/magento maintenance:enable

# Cleanup
rm -rf ./generated/* ./pub/static/adminhtml/* ./pub/static/frontend/* ./var/cache/* ./var/page_cache/* ./var/view_preprocessed/*

# Flush cache
php bin/magento cache:flush

# Update required components
composer update

# Run setup scripts
php bin/magento setup:db-data:upgrade
php bin/magento setup:db-schema:upgrade

# Compile code
# php bin/magento setup:di:compile

# Reindex
php bin/magento indexer:reindex

# Resize images
php bin/magento catalog:images:resize

# Set themes as physical
php bin/magento dg-util:set-themes

# Deploy static view files
php bin/magento setup:static-content:deploy en_US -f --no-html-minify

# Disable maintenance mode
php bin/magento maintenance:disable
